# Tetracycline Resistance Model

(c) 2021 Tom Röschinger. This work is licensed under a 
[Creative Commons Attribution License CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/). 
All code contained herein is licensed under an 
[MIT license](https://opensource.org/licenses/MIT).

In [2]:
using SymPy, Polynomials, Jedi, ColorSchemes, Turing, Distributions, LinearAlgebra

# Comment this out if Jedi.jl is not installed
#Jedi.default_gr!()

In this notebook we go through everything bla bla

In [3]:
@syms a λ λ_0 κ_t K_d Δr j V_0 a_ex K_M P_out P_in

(a, λ, λ_0, κ_t, K_d, Δr, j, V_0, a_ex, K_M, P_out, P_in)

In [48]:
eq1 = (a * λ) / (κ_t * K_d) - Δr * (1 - λ/λ_0)

     ⎛  λ     ⎞    a⋅λ  
- Δr⋅⎜- ── + 1⎟ + ──────
     ⎝  λ₀    ⎠   K_d⋅κₜ

In [49]:
eq2 = a^2 * (-λ - P_out) + a * (-λ * K_M  + P_in * a_ex - P_out * K_M - V_0 * λ/λ_0 ) + P_in * a_ex * K_M

               2                 ⎛                              V₀⋅λ⎞
K_M⋅Pᵢₙ⋅aₑₓ + a ⋅(-Pₒᵤₜ - λ) + a⋅⎜-K_M⋅Pₒᵤₜ - K_M⋅λ + Pᵢₙ⋅aₑₓ - ────⎟
                                 ⎝                               λ₀ ⎠

In [50]:
expr1 = solve(eq1, a)[1]

K_d⋅Δr⋅κₜ⋅(-λ + λ₀)
───────────────────
        λ⋅λ₀       

In [51]:
expr2 = subs(eq2, a=>expr1)

                                                                        ⎛     
                 2   2   2                      2   K_d⋅Δr⋅κₜ⋅(-λ + λ₀)⋅⎜-K_M⋅
              K_d ⋅Δr ⋅κₜ ⋅(-Pₒᵤₜ - λ)⋅(-λ + λ₀)                        ⎝     
K_M⋅Pᵢₙ⋅aₑₓ + ─────────────────────────────────── + ──────────────────────────
                              2   2                                           
                             λ ⋅λ₀                                            

                         V₀⋅λ⎞
Pₒᵤₜ - K_M⋅λ + Pᵢₙ⋅aₑₓ - ────⎟
                          λ₀ ⎠
──────────────────────────────
λ⋅λ₀                          
                              

In [53]:
expr3 = expr2 * λ^2 * λ_0^2

       ⎛                                                                      
       ⎜                 2   2   2                      2   K_d⋅Δr⋅κₜ⋅(-λ + λ₀
 2   2 ⎜              K_d ⋅Δr ⋅κₜ ⋅(-Pₒᵤₜ - λ)⋅(-λ + λ₀)                      
λ ⋅λ₀ ⋅⎜K_M⋅Pᵢₙ⋅aₑₓ + ─────────────────────────────────── + ──────────────────
       ⎜                              2   2                                   
       ⎝                             λ ⋅λ₀                                    

  ⎛                              V₀⋅λ⎞⎞
)⋅⎜-K_M⋅Pₒᵤₜ - K_M⋅λ + Pᵢₙ⋅aₑₓ - ────⎟⎟
  ⎝                               λ₀ ⎠⎟
──────────────────────────────────────⎟
        λ⋅λ₀                          ⎟
                                      ⎠

In [54]:
expr4 = factor(expr3)

                    2                             2                  3        
K_M⋅K_d⋅Pₒᵤₜ⋅Δr⋅κₜ⋅λ ⋅λ₀ - K_M⋅K_d⋅Pₒᵤₜ⋅Δr⋅κₜ⋅λ⋅λ₀  + K_M⋅K_d⋅Δr⋅κₜ⋅λ ⋅λ₀ - K_

             2   2                2   2      2        2   2  2        2       
M⋅K_d⋅Δr⋅κₜ⋅λ ⋅λ₀  + K_M⋅Pᵢₙ⋅aₑₓ⋅λ ⋅λ₀  - K_d ⋅Pₒᵤₜ⋅Δr ⋅κₜ ⋅λ  + 2⋅K_d ⋅Pₒᵤₜ⋅Δ

 2   2           2        2   2   2      2   2   2  3        2   2   2  2     
r ⋅κₜ ⋅λ⋅λ₀ - K_d ⋅Pₒᵤₜ⋅Δr ⋅κₜ ⋅λ₀  - K_d ⋅Δr ⋅κₜ ⋅λ  + 2⋅K_d ⋅Δr ⋅κₜ ⋅λ ⋅λ₀ -

    2   2   2     2                      2                            2       
 K_d ⋅Δr ⋅κₜ ⋅λ⋅λ₀  - K_d⋅Pᵢₙ⋅aₑₓ⋅Δr⋅κₜ⋅λ ⋅λ₀ + K_d⋅Pᵢₙ⋅aₑₓ⋅Δr⋅κₜ⋅λ⋅λ₀  + K_d⋅

          3                 2   
V₀⋅Δr⋅κₜ⋅λ  - K_d⋅V₀⋅Δr⋅κₜ⋅λ ⋅λ₀

In [55]:
expr5 = collect(expr4, λ)

     2        2   2   2    3 ⎛                      2   2   2               ⎞ 
- K_d ⋅Pₒᵤₜ⋅Δr ⋅κₜ ⋅λ₀  + λ ⋅⎝K_M⋅K_d⋅Δr⋅κₜ⋅λ₀ - K_d ⋅Δr ⋅κₜ  + K_d⋅V₀⋅Δr⋅κₜ⎠ 

   2 ⎛                                        2                 2      2      
+ λ ⋅⎝K_M⋅K_d⋅Pₒᵤₜ⋅Δr⋅κₜ⋅λ₀ - K_M⋅K_d⋅Δr⋅κₜ⋅λ₀  + K_M⋅Pᵢₙ⋅aₑₓ⋅λ₀  - K_d ⋅Pₒᵤₜ⋅

  2   2        2   2   2                                            ⎞     ⎛   
Δr ⋅κₜ  + 2⋅K_d ⋅Δr ⋅κₜ ⋅λ₀ - K_d⋅Pᵢₙ⋅aₑₓ⋅Δr⋅κₜ⋅λ₀ - K_d⋅V₀⋅Δr⋅κₜ⋅λ₀⎠ + λ⋅⎝- K

                    2        2        2   2         2   2   2   2             
_M⋅K_d⋅Pₒᵤₜ⋅Δr⋅κₜ⋅λ₀  + 2⋅K_d ⋅Pₒᵤₜ⋅Δr ⋅κₜ ⋅λ₀ - K_d ⋅Δr ⋅κₜ ⋅λ₀  + K_d⋅Pᵢₙ⋅aₑ

          2⎞
ₓ⋅Δr⋅κₜ⋅λ₀ ⎠

In [56]:
println(expr5.coeff(λ, 4))
expr5.coeff(λ, 4)

0


0

In [57]:
println(expr5.coeff(λ, 3))
factor(expr5.coeff(λ, 3), K_d)

K_M*K_d*Δr*κ_t*λ_0 - K_d^2*Δr^2*κ_t^2 + K_d*V_0*Δr*κ_t


-K_d⋅Δr⋅κₜ⋅(-K_M⋅λ₀ + K_d⋅Δr⋅κₜ - V₀)

In [58]:
println(expr5.coeff(λ, 2))
factor(expr5.coeff(λ, 2), K_d)

K_M*K_d*P_out*Δr*κ_t*λ_0 - K_M*K_d*Δr*κ_t*λ_0^2 + K_M*P_in*a_ex*λ_0^2 - K_d^2*P_out*Δr^2*κ_t^2 + 2*K_d^2*Δr^2*κ_t^2*λ_0 - K_d*P_in*a_ex*Δr*κ_t*λ_0 - K_d*V_0*Δr*κ_t*λ_0


              2      2 ⎛       2   2       2   2   ⎞       ⎛                  
K_M⋅Pᵢₙ⋅aₑₓ⋅λ₀  - K_d ⋅⎝Pₒᵤₜ⋅Δr ⋅κₜ  - 2⋅Δr ⋅κₜ ⋅λ₀⎠ - K_d⋅⎝-K_M⋅Pₒᵤₜ⋅Δr⋅κₜ⋅λ₀

               2                                 ⎞
 + K_M⋅Δr⋅κₜ⋅λ₀  + Pᵢₙ⋅aₑₓ⋅Δr⋅κₜ⋅λ₀ + V₀⋅Δr⋅κₜ⋅λ₀⎠

In [59]:
println(expr5.coeff(λ, 1))
factor(expr5.coeff(λ, 1), K_d)

-K_M*K_d*P_out*Δr*κ_t*λ_0^2 + 2*K_d^2*P_out*Δr^2*κ_t^2*λ_0 - K_d^2*Δr^2*κ_t^2*λ_0^2 + K_d*P_in*a_ex*Δr*κ_t*λ_0^2


K_d⋅Δr⋅κₜ⋅λ₀⋅(-K_M⋅Pₒᵤₜ⋅λ₀ + K_d⋅(2⋅Pₒᵤₜ⋅Δr⋅κₜ - Δr⋅κₜ⋅λ₀) + Pᵢₙ⋅aₑₓ⋅λ₀)

In [60]:
println(expr5.coeff(λ, 0))
expr5.coeff(λ, 0)

-K_d^2*P_out*Δr^2*κ_t^2*λ_0^2


    2        2   2   2
-K_d ⋅Pₒᵤₜ⋅Δr ⋅κₜ ⋅λ₀ 

In [78]:
expr5

     2        2   2   2    3 ⎛                      2   2   2               ⎞ 
- K_d ⋅Pₒᵤₜ⋅Δr ⋅κₜ ⋅λ₀  + λ ⋅⎝K_M⋅K_d⋅Δr⋅κₜ⋅λ₀ - K_d ⋅Δr ⋅κₜ  + K_d⋅V₀⋅Δr⋅κₜ⎠ 

   2 ⎛                                        2                 2      2      
+ λ ⋅⎝K_M⋅K_d⋅Pₒᵤₜ⋅Δr⋅κₜ⋅λ₀ - K_M⋅K_d⋅Δr⋅κₜ⋅λ₀  + K_M⋅Pᵢₙ⋅aₑₓ⋅λ₀  - K_d ⋅Pₒᵤₜ⋅

  2   2        2   2   2                                            ⎞     ⎛   
Δr ⋅κₜ  + 2⋅K_d ⋅Δr ⋅κₜ ⋅λ₀ - K_d⋅Pᵢₙ⋅aₑₓ⋅Δr⋅κₜ⋅λ₀ - K_d⋅V₀⋅Δr⋅κₜ⋅λ₀⎠ + λ⋅⎝- K

                    2        2        2   2         2   2   2   2             
_M⋅K_d⋅Pₒᵤₜ⋅Δr⋅κₜ⋅λ₀  + 2⋅K_d ⋅Pₒᵤₜ⋅Δr ⋅κₜ ⋅λ₀ - K_d ⋅Δr ⋅κₜ ⋅λ₀  + K_d⋅Pᵢₙ⋅aₑ

          2⎞
ₓ⋅Δr⋅κₜ⋅λ₀ ⎠

In [79]:

function solve_polynomial(aex, λ0, κt, Kd, KM, j, V0, Δr)
    c = zeros(4)
    c1 = κt * Kd * Δr
    c[4] = c1 * (KM * λ0 - c1 + V0)
    c[3] = KM * j * aex * λ0^2 - c1^2 * (j - 2λ0) - c1 * λ0 * (-KM * j  + KM * λ0 + j * aex + V0)
    c[2] = c1 * λ0 * (-KM * j * λ0 + c1 * (2j - λ0) + j * aex * λ0)
    c[1] = -Kd^2*j*Δr^2*κt^2*λ0^2
    pol = Polynomial(c)
    return Polynomials.roots(pol)
end


solve_polynomial (generic function with 1 method)

In [85]:
_aex = 0  # µM
_λ0 = 0.68  # h**-1
_κt = 0.06  # µM**-1 h**-1
_Kd = .1  # µM
_KM = 100 # µM
_j = 10# h**-1
Pin = 10
Pout = 3
_V0 = 0
_Δr = 46.5  # µM


a_ex_range = [0, 1]
sol_list = zeros(ComplexF64, 3, length(a_ex_range))
for (i, x) in enumerate(a_ex_range)
    # Pack parameters together
    args = (x, _λ0, _κt, _Kd, _KM, _j, _V0, _Δr)
    # Find roots
    sol_list[:, i] = solve_polynomial(args...)
end

In [86]:
sol_list[:, 2]

3-element Vector{ComplexF64}:
     -33.89338895304312 + 0.0im
 -0.0028014943665923423 + 0.0im
    0.20062909641230975 + 0.0im

In [21]:
p = scatter(
    ylim=[0, 1],
    xscale=:log,
    legendtitle = "V0",
    ylabel="λ/λ0",
    xlabel="a_ex",
    title="Is this the right font?"
)

V_0_list = [0, 1000, 5000, 10000]
for (_V0, c) in zip(V_0_list, palette(:BuPu_6)[2:end])
    y = []
    x = Float64[]
    for i in 1:length(a_ex_range)
        args = (a_ex_range[i], _λ0, _κt, _Kd, _KM, _j, _V0, _Δr)
        solutions = solve_polynomial(args...)
        _y = [imag(x) == 0 ? real(x)/_λ0 : missing for x in solutions]
        push!(y, _y...)
        _x = ones(length(_y)) .* a_ex_range[i]
        push!(x, _x...)
    end
    scatter!(p, x, y, color=c, label="$_V0")
end
savefig(p, "res_model.pdf")
p

LoadError: UndefVarError: scatter not defined

## Writing Generative Model

Now we are going to write down the model in a Bayesian way and try out various priors.

\begin{align}
\lambda_0 &= 0.68 h^{-1},\\[.5em]
\kappa_t &= 0.06 \mu M^{-1} h^{-1},\\[.5em]
K_d &= 0.1 \mu M,\\[.5em]
K_M &= 10 \mu M,\\[.5em]
\Delta r &= 46.5 \mu M,\\[.5em]
\log j &\sim \text{Norm}(2, 2),\\[.5em]
j &= 10^{\log j} \times 1 s^{-1},\\[.5em]
\log P_\mathrm{in} &\sim \text{Norm}(2, 2),\\[.5em]
P_\mathrm{in} &= 10^{\log P_\mathrm{in}} \times 1 s^{-1},\\[.5em]
\log P_\mathrm{out} &\sim \text{Norm}(2, 2),\\[.5em]
P_\mathrm{out} &= 10^{\log P_\mathrm{out}} \times 1 s^{-1},\\[.5em]
\log V_0 &\sim \text{Norm}(2, 2),\\[.5em]
V_0  &= 10^{\log V_0 } \times 1 \mu M s^{-1}
\end{align}

In [192]:
@model function fit_growth(growth_rates, aex_arr)
    
    log_j ~ Normal(2, .2)
    log_V0 ~ Normal(2, .2)
    log_sigma ~ Normal(-3, 1)
    
    sigma = float(10^log_sigma)
    j = 10^log_j
    V0 = 10^log_V0
    
    λ0 = 0.68  
    κt = 0.06
    Kd = .1
    KM = 10
    Δr = 46.5
    
    for (i, aex) in enumerate(aex_arr)
        λ = growth_rates[i]
        println(i)
        println(typeof(V0))
        x = [aex, λ0, κt, Kd, KM, j, V0, Δr]
        solutions = solve_polynomial(x)
        
        #y = [imag(x) == 0 ? real(x)/λ0 : missing for x in solutions]
        #y = filter(x -> !ismissing(x) && (x > 0), y)
        #if length(y) == 3
            #deleteat!(y, 2)
            #opt_y = y[argmin([(λ - root)^2 for root in y])]
        #else
            #opt_y = y[1]
       #end
        
        #println(opt_y)
        #println(typeof(opt_y))
        #println()
        #growth_rates[i] ~ Normal(opt_y / λ0, sigma)
    end
    
end

fit_growth (generic function with 3 methods)

In [193]:
y = Float64[]
for i in 1:length(a_ex_range)
    args = (a_ex_range[i], _λ0, _κt, _Kd, _KM, _j, 0, _Δr)
    solutions = solve_polynomial(args...)
    _y = [imag(x) == 0 ? real(x)/_λ0 : missing for x in solutions]
    push!(y, _y[1])
end

In [194]:
chn = sample(fit_growth(y, a_ex_range), NUTS(0.65), 100)


1
Float64
2
Float64
3
Float64
4
Float64
5
Float64
6
Float64
7
Float64
8
Float64
9
Float64
10
Float64
11
Float64
12
Float64
13
Float64
14
Float64
15
Float64
16
Float64
17
Float64
18
Float64
19
Float64
20
Float64
21
Float64
22
Float64
23
Float64
24
Float64
25
Float64
26
Float64
27
Float64
28
Float64
29
Float64
30
Float64
31
Float64
32
Float64
33
Float64
34
Float64
35
Float64
36
Float64
37
Float64
38
Float64
39
Float64
40
Float64
41
Float64
42
Float64
43
Float64
44
Float64
45
Float64
46
Float64
47
Float64
48
Float64
49
Float64
50
Float64
51
Float64
52
Float64
53
Float64
54
Float64
55
Float64
56
Float64
57
Float64
58
Float64
59
Float64
60
Float64
61
Float64
62
Float64
63
Float64
64
Float64
65
Float64
66
Float64
67
Float64
68
Float64
69
Float64
70
Float64
71
Float64
72
Float64
73
Float64
74
Float64
75
Float64
76
Float64
77
Float64
78
Float64
79
Float64
80
Float64
81
Float64
82
Float64
83
Float64
84
Float64
85
Float64
86
Float64
87
Float64
88
Float64
89
Float64
90
Float64
91
Float64
92
Float

LoadError: MethodError: no method matching eigvals!(::Matrix{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#1"{DynamicPPL.TypedVarInfo{NamedTuple{(:log_j, :log_V0, :log_sigma), Tuple{DynamicPPL.Metadata{Dict{AbstractPPL.VarName{:log_j, Tuple{}}, Int64}, Vector{Normal{Float64}}, Vector{AbstractPPL.VarName{:log_j, Tuple{}}}, Vector{Float64}, Vector{Set{DynamicPPL.Selector}}}, DynamicPPL.Metadata{Dict{AbstractPPL.VarName{:log_V0, Tuple{}}, Int64}, Vector{Normal{Float64}}, Vector{AbstractPPL.VarName{:log_V0, Tuple{}}}, Vector{Float64}, Vector{Set{DynamicPPL.Selector}}}, DynamicPPL.Metadata{Dict{AbstractPPL.VarName{:log_sigma, Tuple{}}, Int64}, Vector{Normal{Float64}}, Vector{AbstractPPL.VarName{:log_sigma, Tuple{}}}, Vector{Float64}, Vector{Set{DynamicPPL.Selector}}}}}, Float64}, DynamicPPL.Model{var"#453#454", (:growth_rates, :aex_arr), (), (), Tuple{Vector{Float64}, Vector{Float64}}, Tuple{}, DynamicPPL.DefaultContext}, DynamicPPL.Sampler{NUTS{Turing.Core.ForwardDiffAD{40}, (), AdvancedHMC.DiagEuclideanMetric}}, DynamicPPL.DefaultContext}, Float64}, Float64, 3}})
Closest candidates are:
  eigvals!(::SymTridiagonal{var"#s832", V} where {var"#s832"<:Union{Float32, Float64}, V<:AbstractVector{var"#s832"}}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/tridiag.jl:293
  eigvals!(::SymTridiagonal{var"#s832", V} where {var"#s832"<:Union{Float32, Float64}, V<:AbstractVector{var"#s832"}}, ::UnitRange) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/tridiag.jl:296
  eigvals!(::SymTridiagonal{var"#s832", V} where {var"#s832"<:Union{Float32, Float64}, V<:AbstractVector{var"#s832"}}, ::Real, ::Real) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/tridiag.jl:301
  ...

In [63]:
chn

LoadError: UndefVarError: chn not defined

In [191]:
?ForwardDiff.Dual

UndefVarError: UndefVarError: ForwardDiff not defined

In [195]:
?eigvals!

search: eigvals! eigvals



```
eigvals!(A; permute::Bool=true, scale::Bool=true, sortby) -> values
```

Same as [`eigvals`](@ref), but saves space by overwriting the input `A`, instead of creating a copy. The `permute`, `scale`, and `sortby` keywords are the same as for [`eigen`](@ref).

!!! note
    The input matrix `A` will not contain its eigenvalues after `eigvals!` is called on it - `A` is used as a workspace.


# Examples

```jldoctest
julia> A = [1. 2.; 3. 4.]
2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

julia> eigvals!(A)
2-element Vector{Float64}:
 -0.3722813232690143
  5.372281323269014

julia> A
2×2 Matrix{Float64}:
 -0.372281  -1.0
  0.0        5.37228
```

---

```
eigvals!(A, B; sortby) -> values
```

Same as [`eigvals`](@ref), but saves space by overwriting the input `A` (and `B`), instead of creating copies.

!!! note
    The input matrices `A` and `B` will not contain their eigenvalues after `eigvals!` is called. They are used as workspaces.


# Examples

```jldoctest
julia> A = [1. 0.; 0. -1.]
2×2 Matrix{Float64}:
 1.0   0.0
 0.0  -1.0

julia> B = [0. 1.; 1. 0.]
2×2 Matrix{Float64}:
 0.0  1.0
 1.0  0.0

julia> eigvals!(A, B)
2-element Vector{ComplexF64}:
 0.0 - 1.0im
 0.0 + 1.0im

julia> A
2×2 Matrix{Float64}:
 -0.0  -1.0
  1.0  -0.0

julia> B
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0
```

---

```
eigvals!(A::Union{SymTridiagonal, Hermitian, Symmetric}, irange::UnitRange) -> values
```

Same as [`eigvals`](@ref), but saves space by overwriting the input `A`, instead of creating a copy. `irange` is a range of eigenvalue *indices* to search for - for instance, the 2nd to 8th eigenvalues.

---

```
eigvals!(A::Union{SymTridiagonal, Hermitian, Symmetric}, vl::Real, vu::Real) -> values
```

Same as [`eigvals`](@ref), but saves space by overwriting the input `A`, instead of creating a copy. `vl` is the lower bound of the interval to search for eigenvalues, and `vu` is the upper bound.
